name: conditions
on: [push] # triggers
jobs:
  hello:
    runs-on: ubuntu-latest # Linux OS. we can have windows or MAC
    steps: # stages
      - name: step1
        if: github.ref == 'refs/heads/feature-**'
        run: echo "Hello world"
      - name: step2
        if: github.ref == 'refs/heads/main'
        run: echo "Hello GitHub actions"
    